name: Runs every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:       # Allow manual triggers
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: |
        python usd_cny.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add --all  # Stages all changes, including new files
        git commit -m "Update dollar_to_yuan.xlsx with new conversion data" || echo "No changes to commit"
        git push

