name: N_type Polysilicon Price

on:
  schedule:
    # Schedule to run every 3 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allows manual trigger of the workflow
    inputs: {}

jobs:
  fetch-price:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Specify your Python version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file with all dependencies

      # Step 4: Run the script
      - name: Run Fetch Script
        run: python DataBI\SMM\smmSolar.py
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Updated Argent prices in Excel" || echo "No changes to commit"
          git push
